# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjust_tau_beta <- function(beta_mat, tau_vec, clus_assign) {
    .Call(`_ClusterZI_adjust_tau_beta`, beta_mat, tau_vec, clus_assign)
}

log_marginal <- function(zi, gmi, beta_k) {
    .Call(`_ClusterZI_log_marginal`, zi, gmi, beta_k)
}

realloc_sm <- function(z, clus_assign, gamma_mat, beta_mat, S, clus_sm) {
    .Call(`_ClusterZI_realloc_sm`, z, clus_assign, gamma_mat, beta_mat, S, clus_sm)
}

log_proposal <- function(clus_after, clus_before, z, gamma_mat, beta_mat, S, clus_sm) {
    .Call(`_ClusterZI_log_proposal`, clus_after, clus_before, z, gamma_mat, beta_mat, S, clus_sm)
}

update_at_risk <- function(z, clus_assign, gamma_mat, beta_mat, r0g, r1g) {
    .Call(`_ClusterZI_update_at_risk`, z, clus_assign, gamma_mat, beta_mat, r0g, r1g)
}

update_beta <- function(z, clus_assign, gamma_mat, beta_mat, mu, s2, s2_MH) {
    .Call(`_ClusterZI_update_beta`, z, clus_assign, gamma_mat, beta_mat, mu, s2, s2_MH)
}

realloc <- function(z, clus_assign, gamma_mat, beta_mat, tau_vec, theta_vec) {
    .Call(`_ClusterZI_realloc`, z, clus_assign, gamma_mat, beta_mat, tau_vec, theta_vec)
}

sm <- function(K_max, z, clus_assign, gamma_mat, beta_mat, tau_vec, theta_vec, launch_iter, mu, s2, r0c, r1c) {
    .Call(`_ClusterZI_sm`, K_max, z, clus_assign, gamma_mat, beta_mat, tau_vec, theta_vec, launch_iter, mu, s2, r0c, r1c)
}

update_tau <- function(clus_assign, tau_vec, theta_vec, U) {
    .Call(`_ClusterZI_update_tau`, clus_assign, tau_vec, theta_vec, U)
}

DM_DM <- function(iter, K_max, z, theta_vec, MH_var, mu, s2, print_iter) {
    .Call(`_ClusterZI_DM_DM`, iter, K_max, z, theta_vec, MH_var, mu, s2, print_iter)
}

DM_ZIDM <- function(iter, K_max, z, theta_vec, launch_iter, MH_var, mu, s2, r0c, r1c, print_iter) {
    .Call(`_ClusterZI_DM_ZIDM`, iter, K_max, z, theta_vec, launch_iter, MH_var, mu, s2, r0c, r1c, print_iter)
}

ZIDM_ZIDM <- function(iter, K_max, z, theta_vec, launch_iter, MH_var, mu, s2, r0g, r1g, r0c, r1c, print_iter) {
    .Call(`_ClusterZI_ZIDM_ZIDM`, iter, K_max, z, theta_vec, launch_iter, MH_var, mu, s2, r0g, r1g, r0c, r1c, print_iter)
}

beta_mat_update <- function(K, iter, z, clus_assign, mu, s2, s2_MH) {
    .Call(`_ClusterZI_beta_mat_update`, K, iter, z, clus_assign, mu, s2, s2_MH)
}

beta_ar_update <- function(K, iter, z, clus_assign, r0g, r1g, mu, s2, s2_MH) {
    .Call(`_ClusterZI_beta_ar_update`, K, iter, z, clus_assign, r0g, r1g, mu, s2, s2_MH)
}

rcpparma_hello_world <- function() {
    .Call(`_ClusterZI_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ClusterZI_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ClusterZI_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ClusterZI_rcpparma_bothproducts`, x)
}

