# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinom_1 <- function(probs_arma) {
    .Call(`_ClusterZI_rmultinom_1`, probs_arma)
}

log_sum_exp <- function(log_unnorm_prob) {
    .Call(`_ClusterZI_log_sum_exp`, log_unnorm_prob)
}

log_marginal <- function(zi, gmi, beta_k) {
    .Call(`_ClusterZI_log_marginal`, zi, gmi, beta_k)
}

logmar_ik <- function(zi, atrisk_i, beta_k) {
    .Call(`_ClusterZI_logmar_ik`, zi, atrisk_i, beta_k)
}

logmar_k <- function(z, atrisk, beta_k) {
    .Call(`_ClusterZI_logmar_k`, z, atrisk, beta_k)
}

logmar <- function(z, atrisk, beta_mat) {
    .Call(`_ClusterZI_logmar`, z, atrisk, beta_mat)
}

log_atrisk <- function(zi, atrisk_i, beta_k, r0g, r1g) {
    .Call(`_ClusterZI_log_atrisk`, zi, atrisk_i, beta_k, r0g, r1g)
}

launch_mcmc <- function(z, atrisk, beta_mat, ci_old, launch_iter, S, samp_clus, nk) {
    .Call(`_ClusterZI_launch_mcmc`, z, atrisk, beta_mat, ci_old, launch_iter, S, samp_clus, nk)
}

log_proposal <- function(z, atrisk, beta_mat, ci_A, ci_B, S, samp_clus) {
    .Call(`_ClusterZI_log_proposal`, z, atrisk, beta_mat, ci_A, ci_B, S, samp_clus)
}

split_beta <- function(nbeta, clus_split, clus_new, beta_old, mu, s2) {
    .Call(`_ClusterZI_split_beta`, nbeta, clus_split, clus_new, beta_old, mu, s2)
}

update_atrisk <- function(z, atrisk_old, beta_mat, ci, r0g, r1g) {
    .Call(`_ClusterZI_update_atrisk`, z, atrisk_old, beta_mat, ci, r0g, r1g)
}

update_beta <- function(z, atrisk, beta_old, ci, mu, s2, s2_MH) {
    .Call(`_ClusterZI_update_beta`, z, atrisk, beta_old, ci, mu, s2, s2_MH)
}

realloc_full <- function(Kmax, z, atrisk, beta_mat, ci_old, theta) {
    .Call(`_ClusterZI_realloc_full`, Kmax, z, atrisk, beta_mat, ci_old, theta)
}

sm <- function(Kmax, nbeta_split, z, atrisk, beta_old, ci_old, theta, mu, s2, launch_iter, r0c, r1c) {
    .Call(`_ClusterZI_sm`, Kmax, nbeta_split, z, atrisk, beta_old, ci_old, theta, mu, s2, launch_iter, r0c, r1c)
}

mod <- function(iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0g, r1g, r0c, r1c, thin) {
    .Call(`_ClusterZI_mod`, iter, Kmax, nbeta_split, z, atrisk_init, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0g, r1g, r0c, r1c, thin)
}

dm_data <- function(Kmax, zi, z_not_i, beta_mat, ci_not_i) {
    .Call(`_ClusterZI_dm_data`, Kmax, zi, z_not_i, beta_mat, ci_not_i)
}

DMDM <- function(iter, Kmax, z, beta_mat, ci_init, theta, thin) {
    .Call(`_ClusterZI_DMDM`, iter, Kmax, z, beta_mat, ci_init, theta, thin)
}

DMZIDM_realloc <- function(z, beta_mat, ci_old, theta) {
    .Call(`_ClusterZI_DMZIDM_realloc`, z, beta_mat, ci_old, theta)
}

DMZIDM_launch_mcmc <- function(z, beta_mat, ci_old, launch_iter, S, samp_clus, nk) {
    .Call(`_ClusterZI_DMZIDM_launch_mcmc`, z, beta_mat, ci_old, launch_iter, S, samp_clus, nk)
}

DMZIDM_log_proposal <- function(z, beta_mat, ci_A, ci_B, S, samp_clus) {
    .Call(`_ClusterZI_DMZIDM_log_proposal`, z, beta_mat, ci_A, ci_B, S, samp_clus)
}

DMZIDM_sm <- function(Kmax, z, beta_mat, ci_old, theta, launch_iter, r0c, r1c) {
    .Call(`_ClusterZI_DMZIDM_sm`, Kmax, z, beta_mat, ci_old, theta, launch_iter, r0c, r1c)
}

DMZIDM <- function(iter, Kmax, z, beta_mat, ci_init, theta, launch_iter, r0c, r1c, thin) {
    .Call(`_ClusterZI_DMZIDM`, iter, Kmax, z, beta_mat, ci_init, theta, launch_iter, r0c, r1c, thin)
}

realloc <- function(Kmax, z, atrisk, beta_mat, ci_old, theta) {
    .Call(`_ClusterZI_realloc`, Kmax, z, atrisk, beta_mat, ci_old, theta)
}

beta_realloc <- function(z, atrisk, beta_old, ci, mu, s2, s2_MH) {
    .Call(`_ClusterZI_beta_realloc`, z, atrisk, beta_old, ci, mu, s2, s2_MH)
}

debug_r <- function(iter, Kmax, z, atrisk, beta_fixed, ci_init, theta) {
    .Call(`_ClusterZI_debug_r`, iter, Kmax, z, atrisk, beta_fixed, ci_init, theta)
}

debug_rb <- function(iter, Kmax, z, atrisk, beta_init, ci_init, theta, mu, s2, s2_MH) {
    .Call(`_ClusterZI_debug_rb`, iter, Kmax, z, atrisk, beta_init, ci_init, theta, mu, s2, s2_MH)
}

debug_brs <- function(iter, Kmax, nbeta_split, z, atrisk, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0c, r1c) {
    .Call(`_ClusterZI_debug_brs`, iter, Kmax, nbeta_split, z, atrisk, beta_init, ci_init, theta, mu, s2, s2_MH, launch_iter, r0c, r1c)
}

rcpparma_hello_world <- function() {
    .Call(`_ClusterZI_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ClusterZI_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ClusterZI_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ClusterZI_rcpparma_bothproducts`, x)
}

